import { Vehicle, Driver, Hotel, Booking, TourGuide } from '@/types'

export const mockVehicles: Vehicle[] = [
  {
    id: '1',
    brand: 'Toyota',
    model: 'Axio',
    year: 2023,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    seats: 5,
    pricePerDay: 2200,
    withDriverPrice: 3200,
    image: 'https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800&h=600&fit=crop&auto=format',
    images: [
      'https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&h=600&fit=crop&auto=format',
    ],
    available: true,
    defaultFuelIncluded: true,
    description: 'Popular Japanese sedan, extremely reliable and fuel-efficient. Perfect for city driving in Dhaka.',
  },
  {
    id: '2',
    brand: 'Toyota',
    model: 'Premio',
    year: 2022,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    seats: 5,
    pricePerDay: 2500,
    withDriverPrice: 3500,
    image: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&h=600&fit=crop&auto=format',
    images: [
      'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800&h=600&fit=crop&auto=format',
    ],
    available: true,
    defaultFuelIncluded: true,
    description: 'Comfortable sedan with premium features, very popular in Bangladesh for business and family use.',
  },
  {
    id: '3',
    brand: 'Toyota',
    model: 'Allion',
    year: 2023,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    seats: 5,
    pricePerDay: 2400,
    withDriverPrice: 3400,
    image: 'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800&h=600&fit=crop&auto=format',
    images: [
      'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&h=600&fit=crop&auto=format',
    ],
    available: true,
    defaultFuelIncluded: true,
    description: 'Stylish and spacious sedan, one of the most popular choices in Bangladesh.',
  },
  {
    id: '4',
    brand: 'Honda',
    model: 'Fit',
    year: 2023,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    seats: 5,
    pricePerDay: 1800,
    withDriverPrice: 2800,
    image: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&h=600&fit=crop&auto=format',
    images: [
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&h=600&fit=crop&auto=format',
    ],
    available: true,
    defaultFuelIncluded: true,
    description: 'Compact and economical hatchback, perfect for navigating busy Dhaka streets.',
  },
  {
    id: '5',
    brand: 'Toyota',
    model: 'Corolla',
    year: 2023,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    seats: 5,
    pricePerDay: 2600,
    withDriverPrice: 3600,
    image: 'https://images.unsplash.com/photo-1623869675781-80aa31012a5a?w=800&h=600&fit=crop&auto=format',
    images: [
      'https://images.unsplash.com/photo-1623869675781-80aa31012a5a?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&h=600&fit=crop&auto=format',
    ],
    available: true,
    defaultFuelIncluded: true,
    description: 'World\'s best-selling car, extremely reliable and comfortable for long journeys.',
  },
  {
    id: '6',
    brand: 'Toyota',
    model: 'Hiace',
    year: 2023,
    fuelType: 'Diesel',
    transmission: 'Manual',
    seats: 15,
    pricePerDay: 4500,
    withDriverPrice: 5500,
    image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&h=600&fit=crop&auto=format',
    images: [
      'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=800&h=600&fit=crop&auto=format',
    ],
    available: true,
    defaultFuelIncluded: true,
    description: 'Large passenger van perfect for group tours, weddings, and family trips across Bangladesh.',
  },
  {
    id: '7',
    brand: 'Nissan',
    model: 'X-Trail',
    year: 2023,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    seats: 7,
    pricePerDay: 3500,
    withDriverPrice: 4500,
    image: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&h=600&fit=crop&auto=format',
    images: [
      'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&h=600&fit=crop&auto=format',
    ],
    available: true,
    defaultFuelIncluded: true,
    description: 'Premium SUV with 7 seats, perfect for comfortable family trips and rough roads.',
  },
  {
    id: '8',
    brand: 'Mitsubishi',
    model: 'Pajero',
    year: 2023,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    seats: 7,
    pricePerDay: 4000,
    withDriverPrice: 5000,
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&h=600&fit=crop&auto=format',
    images: [
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&h=600&fit=crop&auto=format',
    ],
    available: true,
    defaultFuelIncluded: true,
    description: 'Powerful 4WD SUV, excellent for Chittagong Hill Tracts and Cox\'s Bazar trips.',
  },
  {
    id: '9',
    brand: 'Honda',
    model: 'Vezel',
    year: 2023,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    seats: 5,
    pricePerDay: 2800,
    withDriverPrice: 3800,
    image: 'https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&h=600&fit=crop&auto=format',
    images: [
      'https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&h=600&fit=crop&auto=format',
    ],
    available: true,
    defaultFuelIncluded: true,
    description: 'Stylish compact SUV, very popular among young professionals in Bangladesh.',
  },
  {
    id: '10',
    brand: 'Toyota',
    model: 'Noah',
    year: 2022,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    seats: 8,
    pricePerDay: 3800,
    withDriverPrice: 4800,
    image: 'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=800&h=600&fit=crop&auto=format',
    images: [
      'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&h=600&fit=crop&auto=format',
    ],
    available: true,
    defaultFuelIncluded: true,
    description: '8-seater hybrid MPV, spacious and fuel-efficient for family trips.',
  },
  {
    id: '11',
    brand: 'Suzuki',
    model: 'Swift',
    year: 2023,
    fuelType: 'Petrol',
    transmission: 'Manual',
    seats: 5,
    pricePerDay: 1600,
    withDriverPrice: 2600,
    image: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&h=600&fit=crop&auto=format',
    images: [
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&h=600&fit=crop&auto=format',
    ],
    available: true,
    defaultFuelIncluded: true,
    description: 'Budget-friendly hatchback, excellent fuel economy for daily commute.',
  },
  {
    id: '12',
    brand: 'Land Cruiser',
    model: 'Prado',
    year: 2023,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    seats: 7,
    pricePerDay: 6000,
    withDriverPrice: 7000,
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&h=600&fit=crop&auto=format',
    images: [
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&h=600&fit=crop&auto=format',
    ],
    available: true,
    defaultFuelIncluded: true,
    description: 'Luxury 4WD SUV, perfect for VIP travel and rough terrain adventures.',
  },
]

export const mockDrivers: Driver[] = [
  {
    id: '1',
    name: 'Abdul Karim',
    photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop&auto=format',
    experience: 8,
    rating: 4.8,
    totalRides: 1250,
    languages: ['Bengali', 'English', 'Hindi'],
    location: 'Dhanmondi',
    city: 'Dhaka',
    bio: 'Professional driver with 8 years of experience. Specializes in city driving and long-distance trips. Very punctual and safety-conscious.',
    available: true,
    pricePerDay: 1500,
    reviews: [
      {
        id: 'd1',
        userName: 'Fatima Begum',
        rating: 5,
        comment: 'Abdul is an excellent driver! Very safe and knows all the routes well. Highly recommended.',
        date: '2024-01-10',
      },
      {
        id: 'd2',
        userName: 'Karim Uddin',
        rating: 5,
        comment: 'Best driver in Dhaka! Professional, courteous, and always on time.',
        date: '2024-01-05',
      },
      {
        id: 'd3',
        userName: 'Rashida Khatun',
        rating: 4,
        comment: 'Great driver, very reliable. Would book again.',
        date: '2023-12-28',
      },
    ],
  },
  {
    id: '2',
    name: 'Mohammad Hasan',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&auto=format',
    experience: 5,
    rating: 4.6,
    totalRides: 890,
    languages: ['Bengali', 'English'],
    location: 'Gulshan',
    city: 'Dhaka',
    bio: 'Young and energetic driver with excellent knowledge of Dhaka city. Great for airport transfers and city tours.',
    available: true,
    pricePerDay: 1300,
    reviews: [
      {
        id: 'd4',
        userName: 'Ahmed Rahman',
        rating: 5,
        comment: 'Mohammad is very professional and friendly. Made our trip comfortable.',
        date: '2024-01-08',
      },
      {
        id: 'd5',
        userName: 'Sadia Islam',
        rating: 4,
        comment: 'Good driver, knows the city well. Very punctual.',
        date: '2024-01-02',
      },
    ],
  },
  {
    id: '3',
    name: 'Rashid Ahmed',
    photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&auto=format',
    experience: 12,
    rating: 4.9,
    totalRides: 2100,
    languages: ['Bengali', 'English', 'Sylheti'],
    location: 'Uttara',
    city: 'Dhaka',
    bio: 'Veteran driver with 12 years of experience. Expert in highway driving and long-distance trips. Very safe and reliable.',
    available: true,
    pricePerDay: 1800,
    reviews: [
      {
        id: 'd6',
        userName: 'Nusrat Jahan',
        rating: 5,
        comment: 'Rashid is the best! Very experienced and safe driver. Perfect for long trips.',
        date: '2024-01-12',
      },
      {
        id: 'd7',
        userName: 'Tariq Mahmud',
        rating: 5,
        comment: 'Excellent driver with great experience. Highly recommended for highway trips.',
        date: '2024-01-07',
      },
      {
        id: 'd8',
        userName: 'Ayesha Rahman',
        rating: 5,
        comment: 'Outstanding service! Rashid is professional and very knowledgeable.',
        date: '2023-12-30',
      },
    ],
  },
  {
    id: '4',
    name: 'Kamal Uddin',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&auto=format',
    experience: 6,
    rating: 4.7,
    totalRides: 950,
    languages: ['Bengali', 'English', 'Chittagonian'],
    location: 'Agrabad',
    city: 'Chittagong',
    bio: 'Professional driver based in Chittagong. Specializes in port area and city driving. Very friendly and helpful.',
    available: true,
    pricePerDay: 1400,
    reviews: [
      {
        id: 'd9',
        userName: 'Mohammad Ali',
        rating: 5,
        comment: 'Kamal is great! Knows Chittagong very well. Very professional.',
        date: '2024-01-09',
      },
      {
        id: 'd10',
        userName: 'Rokeya Khatun',
        rating: 4,
        comment: 'Good driver, reliable and safe. Would recommend.',
        date: '2024-01-03',
      },
    ],
  },
  {
    id: '5',
    name: 'Shahid Rahman',
    photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop&auto=format',
    experience: 10,
    rating: 4.8,
    totalRides: 1650,
    languages: ['Bengali', 'English'],
    location: 'Banani',
    city: 'Dhaka',
    bio: 'Experienced driver with excellent track record. Specializes in corporate transfers and VIP services.',
    available: true,
    pricePerDay: 1700,
    reviews: [
      {
        id: 'd11',
        userName: 'Hasan Mahmud',
        rating: 5,
        comment: 'Shahid is excellent for business trips. Very professional and punctual.',
        date: '2024-01-11',
      },
      {
        id: 'd12',
        userName: 'Farida Begum',
        rating: 5,
        comment: 'Best driver for corporate use. Highly professional service.',
        date: '2024-01-06',
      },
    ],
  },
  {
    id: '6',
    name: 'Tariq Mahmud',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&auto=format',
    experience: 7,
    rating: 4.7,
    totalRides: 1100,
    languages: ['Bengali', 'English', 'Hindi'],
    location: 'Mirpur',
    city: 'Dhaka',
    bio: 'Reliable driver with good knowledge of Dhaka and surrounding areas. Great for family trips and daily commutes.',
    available: true,
    pricePerDay: 1350,
    reviews: [
      {
        id: 'd13',
        userName: 'Jahanara Begum',
        rating: 4,
        comment: 'Tariq is a good driver, very patient and safe. Good for family trips.',
        date: '2024-01-04',
      },
      {
        id: 'd14',
        userName: 'Abdul Kader',
        rating: 5,
        comment: 'Excellent driver! Very reliable and knows all routes.',
        date: '2023-12-29',
      },
    ],
  },
]

export const mockHotels: Hotel[] = [
  {
    id: '1',
    name: 'Grand Dhaka Hotel',
    location: '123 Dhanmondi Road',
    city: 'Dhaka',
    pricePerNight: 3500,
    images: [
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1582719508251-b38c27cd32a1?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&h=600&fit=crop&auto=format',
    ],
    availableRooms: 12,
    totalRooms: 20,
    rating: 4.5,
    amenities: ['WiFi', 'AC', 'Swimming Pool', 'Restaurant', '24/7 Reception', 'Parking'],
    description: 'Luxurious hotel in the heart of Dhaka with modern amenities and excellent service.',
    reviews: [
      {
        id: '1',
        userName: 'Rashid Ahmed',
        rating: 5,
        comment: 'Excellent hotel with great service. The staff was very helpful and the rooms were clean and comfortable.',
        date: '2024-01-15',
      },
      {
        id: '2',
        userName: 'Fatima Begum',
        rating: 4,
        comment: 'Good location and nice facilities. Breakfast was delicious. Would stay again.',
        date: '2024-01-10',
      },
      {
        id: '3',
        userName: 'Karim Uddin',
        rating: 5,
        comment: 'Perfect stay! The hotel exceeded our expectations. Highly recommended.',
        date: '2024-01-05',
      },
    ],
  },
  {
    id: '2',
    name: 'Chittagong Bay Hotel',
    location: '456 Agrabad Commercial Area',
    city: 'Chittagong',
    pricePerNight: 3200,
    images: [
      'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1596436889106-be35e843f974?w=800&h=600&fit=crop&auto=format',
    ],
    availableRooms: 8,
    totalRooms: 15,
    rating: 4.7,
    amenities: ['WiFi', 'AC', 'Breakfast', 'Gym', 'Business Center', 'Room Service'],
    description: 'Modern hotel with great facilities near the commercial area. Perfect for business travelers.',
    reviews: [
      {
        id: '4',
        userName: 'Mohammad Hasan',
        rating: 5,
        comment: 'Great hotel for business trips. Fast WiFi and comfortable rooms. Staff is professional.',
        date: '2024-01-12',
      },
      {
        id: '5',
        userName: 'Ayesha Rahman',
        rating: 4,
        comment: 'Nice hotel with good amenities. The location is convenient for shopping and business.',
        date: '2024-01-08',
      },
    ],
  },
  {
    id: '3',
    name: 'Cox\'s Bazar Beach Resort',
    location: '789 Marine Drive',
    city: 'Cox\'s Bazar',
    pricePerNight: 4500,
    images: [
      'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&h=600&fit=crop&auto=format',
    ],
    availableRooms: 15,
    totalRooms: 25,
    rating: 4.6,
    amenities: ['WiFi', 'AC', 'Beach Access', 'Pool', 'Spa', 'Restaurant', 'Bar'],
    description: 'Beautiful beachfront resort with stunning ocean views. Perfect for a relaxing vacation.',
    reviews: [
      {
        id: '6',
        userName: 'Sadia Islam',
        rating: 5,
        comment: 'Amazing beachfront location! The view from the room was breathtaking. Great service and facilities.',
        date: '2024-01-18',
      },
      {
        id: '7',
        userName: 'Tariq Mahmud',
        rating: 4,
        comment: 'Beautiful resort right on the beach. The pool area is great and the food was excellent.',
        date: '2024-01-14',
      },
      {
        id: '8',
        userName: 'Nusrat Jahan',
        rating: 5,
        comment: 'Perfect for a family vacation. Kids loved the pool and beach access. Highly recommended!',
        date: '2024-01-11',
      },
    ],
  },
  {
    id: '4',
    name: 'Heritage Dhaka Hotel',
    location: '321 Old Dhaka',
    city: 'Dhaka',
    pricePerNight: 2800,
    images: [
      'https://images.unsplash.com/photo-1596436889106-be35e843f974?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1582719508251-b38c27cd32a1?w=800&h=600&fit=crop&auto=format',
    ],
    availableRooms: 10,
    totalRooms: 18,
    rating: 4.4,
    amenities: ['WiFi', 'AC', 'Heritage Tours', 'Rooftop Restaurant', 'Cultural Events'],
    description: 'Experience the charm of old Dhaka in this beautifully restored heritage hotel.',
    reviews: [
      {
        id: '9',
        userName: 'Abdul Kader',
        rating: 4,
        comment: 'Unique heritage hotel with character. The rooftop restaurant has great views of old Dhaka.',
        date: '2024-01-09',
      },
      {
        id: '10',
        userName: 'Rokeya Khatun',
        rating: 4,
        comment: 'Loved the cultural atmosphere. The hotel is well-maintained and the staff is friendly.',
        date: '2024-01-06',
      },
    ],
  },
]

export const mockTourGuides: TourGuide[] = [
  {
    id: '1',
    name: 'Ahmed Rahman',
    photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop&auto=format',
    location: 'Old Dhaka',
    city: 'Dhaka',
    languages: ['Bengali', 'English', 'Hindi'],
    specialties: ['Historical Tours', 'Cultural Heritage', 'Food Tours'],
    experience: 8,
    rating: 4.8,
    totalTours: 450,
    pricePerDay: 2500,
    bio: 'Passionate local guide with deep knowledge of Dhaka\'s rich history and culture. Specializes in showing visitors the hidden gems of Old Dhaka.',
    available: true,
    reviews: [
      {
        id: 'tg1',
        userName: 'Sarah Johnson',
        rating: 5,
        comment: 'Ahmed was an excellent guide! He showed us places we never would have found on our own. Very knowledgeable and friendly.',
        date: '2024-01-10',
      },
      {
        id: 'tg2',
        userName: 'Michael Chen',
        rating: 5,
        comment: 'Best tour guide in Dhaka! His food tour was amazing. Highly recommend booking with Ahmed.',
        date: '2024-01-05',
      },
      {
        id: 'tg3',
        userName: 'Fatima Ali',
        rating: 4,
        comment: 'Great experience! Ahmed knows all the historical sites and tells fascinating stories.',
        date: '2023-12-28',
      },
    ],
  },
  {
    id: '2',
    name: 'Rashida Begum',
    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop&auto=format',
    location: 'Gulshan',
    city: 'Dhaka',
    languages: ['Bengali', 'English'],
    specialties: ['City Tours', 'Shopping Tours', 'Modern Dhaka'],
    experience: 5,
    rating: 4.7,
    totalTours: 320,
    pricePerDay: 2200,
    bio: 'Friendly and energetic guide specializing in modern Dhaka. Perfect for first-time visitors who want to explore the city\'s contemporary side.',
    available: true,
    reviews: [
      {
        id: 'tg4',
        userName: 'David Wilson',
        rating: 5,
        comment: 'Rashida made our first visit to Dhaka unforgettable. She\'s very professional and knows all the best spots.',
        date: '2024-01-08',
      },
      {
        id: 'tg5',
        userName: 'Emma Brown',
        rating: 4,
        comment: 'Great shopping tour! Rashida took us to amazing local markets and helped us bargain.',
        date: '2024-01-02',
      },
    ],
  },
  {
    id: '3',
    name: 'Karim Uddin',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&auto=format',
    location: 'Cox\'s Bazar',
    city: 'Cox\'s Bazar',
    languages: ['Bengali', 'English', 'Rohingya'],
    specialties: ['Beach Tours', 'Adventure Tours', 'Nature Tours'],
    experience: 10,
    rating: 4.9,
    totalTours: 680,
    pricePerDay: 3000,
    bio: 'Experienced guide specializing in Cox\'s Bazar and surrounding areas. Expert in beach activities, hiking, and nature exploration.',
    available: true,
    reviews: [
      {
        id: 'tg6',
        userName: 'James Taylor',
        rating: 5,
        comment: 'Karim is the best! He organized an amazing beach and nature tour. Very professional and safety-conscious.',
        date: '2024-01-12',
      },
      {
        id: 'tg7',
        userName: 'Lisa Anderson',
        rating: 5,
        comment: 'Incredible experience! Karim knows all the hidden beaches and best sunset spots. Worth every taka!',
        date: '2024-01-07',
      },
      {
        id: 'tg8',
        userName: 'Robert Martinez',
        rating: 5,
        comment: 'Outstanding guide! Karim made our Cox\'s Bazar trip memorable. Highly recommended!',
        date: '2023-12-30',
      },
    ],
  },
  {
    id: '4',
    name: 'Nusrat Jahan',
    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop&auto=format',
    location: 'Sylhet',
    city: 'Sylhet',
    languages: ['Bengali', 'English', 'Sylheti'],
    specialties: ['Tea Garden Tours', 'Nature Tours', 'Cultural Tours'],
    experience: 6,
    rating: 4.6,
    totalTours: 280,
    pricePerDay: 2000,
    bio: 'Local Sylhet guide with expertise in tea gardens and natural attractions. Passionate about sharing the beauty of Sylhet.',
    available: true,
    reviews: [
      {
        id: 'tg9',
        userName: 'Jennifer Lee',
        rating: 5,
        comment: 'Nusrat showed us the most beautiful tea gardens! Her knowledge of the area is impressive.',
        date: '2024-01-09',
      },
      {
        id: 'tg10',
        userName: 'Thomas White',
        rating: 4,
        comment: 'Great guide for exploring Sylhet. Very friendly and accommodating.',
        date: '2024-01-03',
      },
    ],
  },
  {
    id: '5',
    name: 'Mohammad Hasan',
    photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop&auto=format',
    location: 'Chittagong',
    city: 'Chittagong',
    languages: ['Bengali', 'English', 'Chittagonian'],
    specialties: ['Port Tours', 'Historical Sites', 'City Exploration'],
    experience: 7,
    rating: 4.7,
    totalTours: 390,
    pricePerDay: 2300,
    bio: 'Experienced Chittagong guide specializing in port history and city exploration. Great for history enthusiasts.',
    available: true,
    reviews: [
      {
        id: 'tg11',
        userName: 'Patricia Davis',
        rating: 5,
        comment: 'Mohammad gave us an excellent tour of Chittagong. His historical knowledge is impressive!',
        date: '2024-01-11',
      },
      {
        id: 'tg12',
        userName: 'Christopher Moore',
        rating: 4,
        comment: 'Good guide, knows the city well. The port tour was particularly interesting.',
        date: '2024-01-06',
      },
    ],
  },
  {
    id: '6',
    name: 'Ayesha Khatun',
    photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop&auto=format',
    location: 'Rajshahi',
    city: 'Rajshahi',
    languages: ['Bengali', 'English'],
    specialties: ['Archaeological Tours', 'Mango Tours', 'Cultural Heritage'],
    experience: 4,
    rating: 4.5,
    totalTours: 180,
    pricePerDay: 1800,
    bio: 'Enthusiastic guide specializing in Rajshahi\'s archaeological sites and mango orchards. Perfect for cultural and agricultural tours.',
    available: true,
    reviews: [
      {
        id: 'tg13',
        userName: 'Amanda Garcia',
        rating: 4,
        comment: 'Ayesha showed us amazing archaeological sites. The mango orchard visit was a bonus!',
        date: '2024-01-04',
      },
      {
        id: 'tg14',
        userName: 'Daniel Rodriguez',
        rating: 5,
        comment: 'Great guide! Very knowledgeable about the history of Rajshahi.',
        date: '2023-12-29',
      },
    ],
  },
]

export const mockBookings: Booking[] = [
  {
    id: '1',
    type: 'vehicle',
    vehicleId: '1',
    driverId: '1',
    startDate: '2024-01-15',
    endDate: '2024-01-18',
    totalPrice: 10500,
    status: 'confirmed',
    createdAt: '2024-01-10',
  },
  {
    id: '2',
    type: 'hotel',
    hotelId: '1',
    startDate: '2024-01-20',
    endDate: '2024-01-23',
    totalPrice: 10500,
    status: 'pending',
    createdAt: '2024-01-12',
  },
  {
    id: '3',
    type: 'tour-guide',
    tourGuideId: '1',
    startDate: '2024-01-25',
    endDate: '2024-01-27',
    totalPrice: 5000,
    status: 'confirmed',
    createdAt: '2024-01-14',
  },
  {
    id: '4',
    type: 'driver',
    driverId: '1',
    startDate: '2024-01-28',
    endDate: '2024-01-30',
    totalPrice: 3000,
    status: 'pending',
    createdAt: '2024-01-15',
  },
]
